### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by ISilence** [ISilence/asteroids.hs#2]
Add render module

- add image loader
- show debug messages
- show HUD
- draw ship, asteroids, projectile (see #4)
- display background
- render whole scene

**Comment by ISilence** [comment]
First part is rendering Asteroids & Ships (see corresponding classes in `Object.hs`) 
You should implement `Drawable` instances for them (be free with extending dependent data)

P.S. Probably for testing you need `Collisible` & `Interactable` instances too, just create temporary stubs.

**Comment by pimka** [comment]
complete
